### ISSUE TITLE
External battery metrics

### ISSUE THREAD

**Issue by alex-popov-tech** [tess1o/go-ecoflow-exporter#1]
Hello! Thank you for building that!

I have a question - any idea, maybe you saw something, about gathering metrics from external batteries connected to delta max?

**Comment by tess1o** [comment]
Hello,

I believe the extra battery metrics have "bms_slave" in their names. You'll have metrics for your main unit and connected external battery using main unit's serial number. 

 I have Delta 2 + extra battery, here is the list of metrics available for my setup (I use prefix "ecoflow" for all metrics):

```
ecoflow_bms_slave_amp
ecoflow_bms_slave_bms_fault
ecoflow_bms_slave_bq_sys_stat_reg
ecoflow_bms_slave_cell_id
ecoflow_bms_slave_cycles
ecoflow_bms_slave_design_cap
ecoflow_bms_slave_err_code
ecoflow_bms_slave_f32_show_soc
ecoflow_bms_slave_full_cap
ecoflow_bms_slave_input_watts
ecoflow_bms_slave_max_cell_temp
ecoflow_bms_slave_max_cell_vol
ecoflow_bms_slave_max_mos_temp
ecoflow_bms_slave_min_cell_temp
ecoflow_bms_slave_min_cell_vol
ecoflow_bms_slave_min_mos_temp
ecoflow_bms_slave_num
ecoflow_bms_slave_open_bms_idx
ecoflow_bms_slave_output_watts
ecoflow_bms_slave_remain_cap
ecoflow_bms_slave_remain_time
ecoflow_bms_slave_soc
ecoflow_bms_slave_soh
ecoflow_bms_slave_sys_ver
ecoflow_bms_slave_tag_chg_amp
ecoflow_bms_slave_temp
ecoflow_bms_slave_type
ecoflow_bms_slave_vol
```

Some of the metrics:

ecoflow_bms_slave_soc - current external battery level in %
ecoflow_bms_slave_output_watts - power output from external battery (to the main unit)
ecoflow_bms_slave_input_watts - power input (during charging)
ecoflow_bms_slave_remain_time - remain time for external battery
ecoflow_bms_slave_cycles - the number of charging cycles  for external battery
ecoflow_bms_slave_temp - temperature 

The rest metrics you probably can figure out from their names. Just to be clear - Ecoflow website for developers has pretty poor documentation and these metrics and not described there at all :)

I might update Grafana dashboard to add info about external battery stats.

**Comment by alex-popov-tech** [comment]
you are right, thank you!

I've copied dashboard and added external battery characteristics myself there, thank you!
![image](https://github.com/tess1o/go-ecoflow-exporter/assets/21224705/8acfa92e-71ca-4c04-b510-ebed14feee34)
