### ISSUE TITLE
Adding alerts

### ISSUE THREAD

**Issue by oleua** [tess1o/go-ecoflow-exporter#19]
Would you mind to add alerting tools to let send notifications when some event happens.

**Comment by tess1o** [comment]
Hello,

You configure Alertmanager to send notifications when some event happens (like battery level is less than X, temperature of BMS is more than Y, etc, etc).
Here is a quick example how to send Telegram notifications: https://github.com/berezhinskiy/ecoflow_exporter/tree/master/docker-compose

I might add some docs how to configure Alertmanager for simple notifications. From exporter code perspective I do not plan any changes on this matter.

Thanks.

**Comment by tess1o** [comment]
Added example how to configure AlertManager: https://github.com/tess1o/go-ecoflow-exporter/blob/main/docs/alertmanager.md
