### ISSUE TITLE
scrap?

### ISSUE THREAD

**Issue by Ndolam** [tess1o/go-ecoflow-exporter#5]
Do you mean "scrape" (2 places in your README) ?

**Comment by tess1o** [comment]
Hello,

This is how often (in seconds) the exporter will call Ecoflow Rest API to get the devices metrics. By default it's 30 seconds, can be changed via environment variables. So each 30 seconds (default value) the exporter makes calls to the Ecoflow Rest Api and gets all the metrics for all linked devices. Then, everything depends on your configuration:
1. If you use Prometheus, then Prometheus each XXX seconds (configurable via prometheus config "scrape_interval") will fetch the metrics from the exporter.
2. If you use TimescaleDB, then once we got metrics from the Ecoflow we will save metrics to the database right away (means we have new rows added to the database each 30 seconds)
3. If you use Redis, then then once we got metrics from the Ecoflow we will save metrics to the Redis right away (we will update TimeSeries in Redis with new data).

Let me know if documentation needs to be updated, I'll do.

Thanks.

**Comment by Ndolam** [comment]
I am not knowledgeable about the terms used in MTQQ and related areas.  Are you telling me that the word "scrap" refers to the polling interval?
For example, when you write
"Other known to me projects use MQTT protocol to scrap the metrics,"
I assumed you were using the word "scrape" to mean "extract information from some output", but your reply to my first message suggests otherwise.

Sorry if I am so out of the MQTT terminology loop that this is a completely bogus issue.

**Comment by tess1o** [comment]
Other Ecoflow exporters use MQTT protocol, I use HTTP REST API. Word "scrape" I took from Prometheus terminology. In Prometheus it means the interval the Prometheus server reads metric from target servers. In my scenario it's the interval to get the metrics from Ecoflow.

I'm ok to change the name to something else if it's confusing.

**Comment by tess1o** [comment]
Hello,

I've updated the README and replaced "scrap" (I meant "scrape") with "fetch". Hope it clears the concern.

Thanks.

**Comment by Ndolam** [comment]
The problem is, you have *not* used the word "scrape".
You used the word "scrap".  Completely a different word.

I just looked and see you edited the readme file and now use the word "fetch".  A much nicer word than "scrape", in my opinion.

Anyway, since your readme no longer has any scrap in it, I think you can close this.

Thanks very much.
